---
driver:
  name: ec2
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
  ssh_key: <%= File.expand_path('.ssh/tkitchen') %>
  security_group_ids: ["default"]
  security_group_ids: default
  availability_zone: ""
  require_chef_omnibus: "10.16.2"
  tags:
    "created-by": "test-kitchen"
  
use_vagrant_berkshelf_plugin: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver:
      image_id: ami-967edcff
      username: ubuntu
      flavor_id: "m1.small"
      tags:
        Name: mysql-ct-Ubuntu-12.04
        owner_name: test-kitchen

  - name: ubuntu-10.04
    driver:
      image_id: ami-9f3906f6
      username: ubuntu
      flavor_id: "m1.small"
      tags:
        Name: mysql-ct-Ubuntu-10.04
        owner_name: test-kitchen

  - name: centos-6.4
    driver:
      image_id: ami-bf5021d6
      username: root
      flavor_id: "m1.small"
      tags:
        Name: mysql-ct-CentOS-6.4
        owner_name: test-kitchen

  - name: centos-5.3
    driver:
      image_id: ami-beda31d7
      username: root
      flavor_id: "m1.small"
      tags:
        Name: mysql-ct-CentOS-5.3
        owner_name: test-kitchen

suites:
  - name: default
    run_list:
      - recipe[minitest-handler]
      - recipe[mysql_component_test]
    attributes: {mysql: { port: 3306, server_root_password: "uR1zaebah0Qu", server_repl_password: "uR1zaebah0Qu", server_debian_password: "uR1zaebah0Qu"}}
  - name: db_create 
    run_list:
      - recipe[minitest-handler]
      - recipe[mysql_component_test::db_create]
    attributes: {
                  mysql: {
                    port: 3306, 
                    server_root_password: "uR1zaebah0Qu", 
                    server_repl_password: "uR1zaebah0Qu",
                    server_debian_password: "uR1zaebah0Qu"
                  },
                  mysql-component: {
                    db_name: "petclinic"
                  }
                }
  - name: user_create 
    run_list:
      - recipe[minitest-handler]
      - recipe[mysql_component_test::user_create]
    attributes: {
                  mysql: {
                    port: 3306,
                    server_root_password: "uR1zaebah0Qu", 
                    server_repl_password: "uR1zaebah0Qu",
                    server_debian_password: "uR1zaebah0Qu"
                  },
                  mysql-component: {
                    db_name: "petclinic",
                    db_pass: "petclinic", 
                    db_user: "petclinic",
                    host: ["192.168.1.1"]
                  }
                }
  - name: sql_query 
    run_list:
      - recipe[minitest-handler]
      - recipe[mysql_component_test::sql_query]
    attributes: {
                  mysql: {
                    port: 3306,
                    server_root_password: "uR1zaebah0Qu", 
                    server_repl_password: "uR1zaebah0Qu",
                    server_debian_password: "uR1zaebah0Qu"
                  },
                  mysql-component: {
                    db_name: "petclinic",
                    db_pass: "petclinic",
                    db_user: "petclinic",
                    host: ["192.168.1.1"],
                    sql_url: ["https://raw.github.com/qubell-bazaar/component-petclinic/master/sql/petclinic-mysql-schema.sql", "https://raw.github.com/qubell-bazaar/component-petclinic/master/sql/petclinic-mysql-dataload.sql"]
                  }
                }
