language: ruby
gemfile:
- gemfiles/travis.gemfile
rvm:
- 1.9.3
env:
  global:
  - secure: VmRspVWrKmR/+kyICYuE9l+p3ZKFJ8no9+nswkseFF3+F42VsD4crakg1Zpmkhr1sDPZiLCAb63ltcgjqBJCAVjXvdfK8soJInCBZi0Yi3Z3ptBDPq6Y9DTB/GW/TypEY2RyNgrgmP19Dyo/rJ0Xr5ns34hABqqvnu1Qv+6+rEI=
  - secure: Lla4zWnbnImBg/jwvd22rL+1z5qrexm2oaY3hKjhv2jrhUumjjUrTYqHAy2LIz4Jde3ZrvFlag7AGJpgumV3o9/X4PPHS5agOP83gbIDsHAy+KBB9ATYvZznPVRFk5eEsiRsj8CiiyLNoDJT8T3+d1u+CfAlXWWbXFS+cBhbdD0=
  - secure: TrLRxt5nN6xKZBuZyhWF8lo9u6OevEzUOzTqBMNVrefx+kVo5x78mMwMZFNgeu7wJ8tNMwBWx17RIsi7t30kHO8m/S7nCN7iiZxsKDC448TJUi2BLcWAzhuyEnGwQRsxa3H/o8JPQcPpVy++wsKTDE4gjv9km6hWtoFwWAqR5gw=
  matrix:
  - KITCHEN_INSTANCE='default-ubuntu-1204'
  - KITCHEN_INSTANCE='default-ubuntu-1004'
  - KITCHEN_INSTANCE='default-centos-64'
  - KITCHEN_INSTANCE='default-centos-53'
  - KITCHEN_INSTANCE='create-db-ubuntu-1204'
  - KITCHEN_INSTANCE='create-db-ubuntu-1004'
  - KITCHEN_INSTANCE='create-db-centos-64'
  - KITCHEN_INSTANCE='create-db-centos-53'
  - KITCHEN_INSTANCE='create-user-ubuntu-1204'
  - KITCHEN_INSTANCE='create-user-ubuntu-1004'
  - KITCHEN_INSTANCE='create-user-centos-64'
  - KITCHEN_INSTANCE='create-user-centos-53'
  - KITCHEN_INSTANCE='file-query-ubuntu-1204'
  - KITCHEN_INSTANCE='file-query-ubuntu-1004'
  - KITCHEN_INSTANCE='file-query-centos-64'
  - KITCHEN_INSTANCE='file-query-centos-53'
script:
- bundle exec foodcritic ./ -f 'any'
- bundle exec kitchen test $KITCHEN_INSTANCE -l debug
after_script:
- bundle exec kitchen destroy $KITCHEN_INSTANCE
notifications:
  email:
  - abutovich@qubell.com
